services:
  shard1_1:
    container_name: shard1-1
    image: mongo
    command: mongod --shardsvr --replSet shard1_rs --port 27017
    ports:
      - 20000:27017

  shard1_2:
    container_name: shard1-2
    image: mongo
    command: mongod --shardsvr --replSet shard1_rs --port 27017
    ports:
      - 20001:27017

  shard2_1:
    container_name: shard2-1
    image: mongo
    command: mongod --shardsvr --replSet shard2_rs --port 27017
    ports:
      - 20002:27017

  shard2_2:
    container_name: shard2-2
    image: mongo
    command: mongod --shardsvr --replSet shard2_rs --port 27017
    ports:
      - 20003:27017
